import { Area, Branch, Customer, Expense, Loan, Product, ProductFinanceOrder, Route, SystemNotification, User, Collection, AgentAttendance } from "@/types";

export const initialBranches: Branch[] = [
  {
    id: "BR-01",
    code: "BR-RJY",
    name: "FinTrack Regional HQ - Rajahmundry",
    city: "Rajahmundry",
    state: "Andhra Pradesh",
    phone: "+91 883 2459800",
  },
  {
    id: "BR-02",
    code: "BR-KKD",
    name: "FinTrack Branch - Kakinada",
    city: "Kakinada",
    state: "Andhra Pradesh",
    phone: "+91 884 2374100",
  }
];

export const initialAreas: Area[] = [
  {
    id: "AREA-01",
    name: "Rajahmundry",
    code: "RJY",
    branchId: "BR-01",
    description: "Main city & Godavari riverbank commercial corridors",
    totalCustomers: 184,
    activeLoansCount: 142,
    totalOutstanding: 1485000,
  },
  {
    id: "AREA-02",
    name: "Kakinada",
    code: "KKD",
    branchId: "BR-02",
    description: "Port city commercial & residential clusters",
    totalCustomers: 142,
    activeLoansCount: 98,
    totalOutstanding: 1120000,
  },
  {
    id: "AREA-03",
    name: "Amalapuram",
    code: "AMP",
    branchId: "BR-01",
    description: "Konaseema agrarian & retail business hub",
    totalCustomers: 96,
    activeLoansCount: 64,
    totalOutstanding: 780000,
  },
  {
    id: "AREA-04",
    name: "Ramachandrapuram",
    code: "RCP",
    branchId: "BR-01",
    description: "Town market center & weekly bazaar belt",
    totalCustomers: 78,
    activeLoansCount: 52,
    totalOutstanding: 590000,
  },
];

export const initialRoutes: Route[] = [
  {
    id: "RT-01",
    name: "Route A - Danavaipeta & Kotagummam",
    code: "RJY-R-A",
    areaId: "AREA-01",
    areaName: "Rajahmundry",
    assignedAgentId: "USR-02",
    assignedAgentName: "Ramesh Varma",
    collectionFrequency: "WEEKLY",
    totalCustomers: 48,
    todayTarget: 28800,
    todayCollected: 21600,
    status: "ACTIVE",
  },
  {
    id: "RT-02",
    name: "Route B - Main Bazaar & Syamala Theatre Road",
    code: "RJY-R-B",
    areaId: "AREA-01",
    areaName: "Rajahmundry",
    assignedAgentId: "USR-03",
    assignedAgentName: "Suresh Babu",
    collectionFrequency: "DAILY",
    totalCustomers: 52,
    todayTarget: 18500,
    todayCollected: 16200,
    status: "ACTIVE",
  },
  {
    id: "RT-03",
    name: "Route C - Bhanugudi & Cinema Road",
    code: "KKD-R-A",
    areaId: "AREA-02",
    areaName: "Kakinada",
    assignedAgentId: "USR-04",
    assignedAgentName: "Venkat Rao",
    collectionFrequency: "WEEKLY",
    totalCustomers: 64,
    todayTarget: 38400,
    todayCollected: 31200,
    status: "ACTIVE",
  },
  {
    id: "RT-04",
    name: "Route D - Clock Tower & Peruru Road",
    code: "AMP-R-A",
    areaId: "AREA-03",
    areaName: "Amalapuram",
    assignedAgentId: "USR-05",
    assignedAgentName: "Prasad Raju",
    collectionFrequency: "MONTHLY",
    totalCustomers: 45,
    todayTarget: 42000,
    todayCollected: 33500,
    status: "ACTIVE",
  },
  {
    id: "RT-05",
    name: "Route E - Market Line & RTC Complex",
    code: "RCP-R-A",
    areaId: "AREA-04",
    areaName: "Ramachandrapuram",
    assignedAgentId: "USR-02",
    assignedAgentName: "Ramesh Varma",
    collectionFrequency: "WEEKLY",
    totalCustomers: 38,
    todayTarget: 22800,
    todayCollected: 18600,
    status: "ACTIVE",
  }
];

export const initialUsers: User[] = [
  {
    id: "USR-01",
    userId: "USR-01",
    name: "Rajesh Kumar (Admin)",
    email: "admin@fintrack.in",
    phone: "+91 98480 12345",
    role: "ADMIN",
    status: "ACTIVE",
    loginId: "ADMIN-01",
    pin: "1002",
    password: "adminpassword",
    recoveryEfficiency: 98.0,
    todayTarget: 150000,
    todayCollected: 94500,
    attendanceStatus: "PRESENT",
    permissions: {
      canCollectCash: true,
      canCollectUPI: true,
      canEditCustomer: true,
      canDisburseLoan: true,
      maxDailyCashLimit: 500000,
    },
  },
  {
    id: "USR-02",
    userId: "USR-02",
    name: "Ramesh Varma",
    email: "ramesh.varma@fintrack.in",
    phone: "+91 99590 88712",
    role: "AGENT",
    status: "ACTIVE",
    loginId: "AGT-RJY-02",
    pin: "1234",
    password: "agentpassword",
    assignedAreaIds: ["AREA-01", "AREA-04"],
    assignedRouteIds: ["RT-01", "RT-05"],
    recoveryEfficiency: 94.2,
    todayTarget: 51600,
    todayCollected: 40200,
    attendanceStatus: "ON_FIELD",
    permissions: {
      canCollectCash: true,
      canCollectUPI: true,
      canEditCustomer: true,
      canDisburseLoan: false,
      maxDailyCashLimit: 75000,
    },
  },
  {
    id: "USR-03",
    userId: "USR-03",
    name: "Suresh Babu",
    email: "suresh.babu@fintrack.in",
    phone: "+91 97033 45210",
    role: "AGENT",
    status: "ACTIVE",
    loginId: "AGT-RJY-03",
    pin: "2389",
    password: "agentpassword",
    assignedAreaIds: ["AREA-01"],
    assignedRouteIds: ["RT-02"],
    recoveryEfficiency: 91.8,
    todayTarget: 18500,
    todayCollected: 16200,
    attendanceStatus: "ON_FIELD",
    permissions: {
      canCollectCash: true,
      canCollectUPI: true,
      canEditCustomer: false,
      canDisburseLoan: false,
      maxDailyCashLimit: 50000,
    },
  },
  {
    id: "USR-04",
    userId: "USR-04",
    name: "Venkat Rao",
    email: "venkat.rao@fintrack.in",
    phone: "+91 94401 67890",
    role: "AGENT",
    status: "ACTIVE",
    loginId: "AGT-KKD-04",
    pin: "8821",
    password: "agentpassword",
    assignedAreaIds: ["AREA-02"],
    assignedRouteIds: ["RT-03"],
    recoveryEfficiency: 88.5,
    todayTarget: 38400,
    todayCollected: 31200,
    attendanceStatus: "ON_FIELD",
    permissions: {
      canCollectCash: true,
      canCollectUPI: true,
      canEditCustomer: true,
      canDisburseLoan: false,
      maxDailyCashLimit: 60000,
    },
  },
  {
    id: "USR-05",
    userId: "USR-05",
    name: "Prasad Raju",
    email: "prasad.raju@fintrack.in",
    phone: "+91 98492 33451",
    role: "AGENT",
    status: "ACTIVE",
    loginId: "AGT-AMP-05",
    pin: "5571",
    password: "agentpassword",
    assignedAreaIds: ["AREA-03"],
    assignedRouteIds: ["RT-04"],
    recoveryEfficiency: 95.0,
    todayTarget: 42000,
    todayCollected: 33500,
    attendanceStatus: "PRESENT",
    permissions: {
      canCollectCash: true,
      canCollectUPI: true,
      canEditCustomer: false,
      canDisburseLoan: true,
      maxDailyCashLimit: 80000,
    },
  },
];

export const initialCustomers: Customer[] = [
  {
    id: "CUST-01",
    customerCode: "CUST-RJY-001",
    name: "B. Satyanarayana Murthy",
    mobileNumber: "+91 98481 22334",
    aadhaarNumber: "7849 2231 9980",
    address: "D.No 12-4-8, Danavaipeta, Rajahmundry",
    areaId: "AREA-01",
    areaName: "Rajahmundry",
    routeId: "RT-01",
    routeName: "Route A - Danavaipeta & Kotagummam",
    assignedAgentId: "USR-02",
    assignedAgentName: "Ramesh Varma",
    occupation: "Wholesale Kirana Store Owner",
    monthlyIncome: 45000,
    referenceName: "M. Subba Rao (Brother-in-law)",
    referenceContact: "+91 94405 11223",
    status: "ACTIVE",
    creditScore: 780,
    joinDate: "2025-04-10",
    totalLoans: 3,
    activeLoanAmount: 20000,
    totalOutstanding: 7200,
  },
  {
    id: "CUST-02",
    customerCode: "CUST-RJY-002",
    name: "P. Lakshmi Durga",
    mobileNumber: "+91 99490 88219",
    aadhaarNumber: "6541 3320 8891",
    address: "Shop #14, Main Bazaar, Rajahmundry",
    areaId: "AREA-01",
    areaName: "Rajahmundry",
    routeId: "RT-02",
    routeName: "Route B - Main Bazaar & Syamala Theatre Road",
    assignedAgentId: "USR-03",
    assignedAgentName: "Suresh Babu",
    occupation: "Saree & Textile Merchant",
    monthlyIncome: 38000,
    referenceName: "V. Srinivas (Husband)",
    referenceContact: "+91 98661 44556",
    status: "ACTIVE",
    creditScore: 740,
    joinDate: "2025-06-15",
    totalLoans: 2,
    activeLoanAmount: 50000,
    totalOutstanding: 23960,
  },
  {
    id: "CUST-03",
    customerCode: "CUST-KKD-003",
    name: "K. Appa Rao",
    mobileNumber: "+91 94901 77654",
    aadhaarNumber: "8890 1245 6712",
    address: "Plot 42, Bhanugudi Junction, Kakinada",
    areaId: "AREA-02",
    areaName: "Kakinada",
    routeId: "RT-03",
    routeName: "Route C - Bhanugudi & Cinema Road",
    assignedAgentId: "USR-04",
    assignedAgentName: "Venkat Rao",
    occupation: "Automobile Garage Owner",
    monthlyIncome: 55000,
    referenceName: "K. Rambabu (Brother)",
    referenceContact: "+91 97000 88990",
    status: "ACTIVE",
    creditScore: 810,
    joinDate: "2025-02-20",
    totalLoans: 4,
    activeLoanAmount: 80000,
    totalOutstanding: 35000,
  },
  {
    id: "CUST-04",
    customerCode: "CUST-AMP-004",
    name: "G. Venkateswara Rao",
    mobileNumber: "+91 98495 66781",
    aadhaarNumber: "4521 9980 3341",
    address: "Near Clock Tower, Amalapuram",
    areaId: "AREA-03",
    areaName: "Amalapuram",
    routeId: "RT-04",
    routeName: "Route D - Clock Tower & Peruru Road",
    assignedAgentId: "USR-05",
    assignedAgentName: "Prasad Raju",
    occupation: "Coconut & Paddy Trader",
    monthlyIncome: 60000,
    referenceName: "N. Suryanarayana",
    referenceContact: "+91 98488 99112",
    status: "ACTIVE",
    creditScore: 765,
    joinDate: "2025-05-12",
    totalLoans: 2,
    activeLoanAmount: 50000,
    totalOutstanding: 19168,
  },
  {
    id: "CUST-05",
    customerCode: "CUST-RCP-005",
    name: "T. Krishna Chaitanya",
    mobileNumber: "+91 97011 22345",
    aadhaarNumber: "3321 8890 4452",
    address: "Market Line, Near RTC Complex, Ramachandrapuram",
    areaId: "AREA-04",
    areaName: "Ramachandrapuram",
    routeId: "RT-05",
    routeName: "Route E - Market Line & RTC Complex",
    assignedAgentId: "USR-02",
    assignedAgentName: "Ramesh Varma",
    occupation: "Electronic Repairs & Accessories",
    monthlyIncome: 32000,
    referenceName: "T. Venkanna (Father)",
    referenceContact: "+91 99512 33445",
    status: "ACTIVE",
    creditScore: 710,
    joinDate: "2025-08-01",
    totalLoans: 1,
    activeLoanAmount: 10000,
    totalOutstanding: 4200,
  },
  {
    id: "CUST-06",
    customerCode: "CUST-RJY-006",
    name: "M. Anitha Kumari",
    mobileNumber: "+91 99890 12344",
    aadhaarNumber: "5567 1234 9876",
    address: "Kotagummam, Rajahmundry",
    areaId: "AREA-01",
    areaName: "Rajahmundry",
    routeId: "RT-01",
    routeName: "Route A - Danavaipeta & Kotagummam",
    assignedAgentId: "USR-02",
    assignedAgentName: "Ramesh Varma",
    occupation: "Tailoring & Boutique",
    monthlyIncome: 25000,
    referenceName: "M. Prasad",
    referenceContact: "+91 98480 55443",
    status: "ACTIVE",
    creditScore: 690,
    joinDate: "2025-09-01",
    totalLoans: 1,
    activeLoanAmount: 15000,
    totalOutstanding: 7800,
  },
  {
    id: "CUST-07",
    customerCode: "CUST-KKD-007",
    name: "V. Chinna Reddemma",
    mobileNumber: "+91 94411 99887",
    aadhaarNumber: "9012 3456 7890",
    address: "Jagannaickpur, Kakinada",
    areaId: "AREA-02",
    areaName: "Kakinada",
    routeId: "RT-03",
    routeName: "Route C - Bhanugudi & Cinema Road",
    assignedAgentId: "USR-04",
    assignedAgentName: "Venkat Rao",
    occupation: "Fish & Sea Food Exporter",
    monthlyIncome: 70000,
    referenceName: "V. Govind Rao",
    referenceContact: "+91 98482 11009",
    status: "BLOCKED",
    creditScore: 520,
    joinDate: "2025-01-10",
    totalLoans: 2,
    activeLoanAmount: 30000,
    totalOutstanding: 28000,
  }
];

export const initialLoans: Loan[] = [
  {
    id: "LN-01",
    loanNumber: "LN-2026-0101",
    customerId: "CUST-01",
    customerName: "B. Satyanarayana Murthy",
    customerCode: "CUST-RJY-001",
    customerPhone: "+91 98481 22334",
    areaId: "AREA-01",
    areaName: "Rajahmundry",
    routeId: "RT-01",
    routeName: "Route A - Danavaipeta & Kotagummam",
    loanType: "WEEKLY",
    principalAmount: 20000,
    interestRatePercentage: 20,
    totalInterestAmount: 4000,
    totalRepayableAmount: 24000,
    installmentAmount: 1200,
    durationUnits: 20,
    disbursementDate: "2026-06-01",
    startDate: "2026-06-08",
    endDate: "2026-10-26",
    totalPaidAmount: 16800,
    outstandingBalance: 7200,
    nextDueDate: "2026-09-21",
    status: "ACTIVE",
    agentId: "USR-02",
    agentName: "Ramesh Varma",
    remarks: "Timely payer with good business turnover",
    installments: Array.from({ length: 20 }, (_, i) => {
      const isPaid = i < 14;
      return {
        installmentNumber: i + 1,
        dueDate: `2026-${String(Math.floor(i / 4) + 6).padStart(2, "0")}-${String((i % 4) * 7 + 8).padStart(2, "0")}`,
        amount: 1200,
        paidAmount: isPaid ? 1200 : 0,
        paidDate: isPaid ? `2026-${String(Math.floor(i / 4) + 6).padStart(2, "0")}-${String((i % 4) * 7 + 8).padStart(2, "0")}` : undefined,
        status: isPaid ? "PAID" : i === 14 ? "DUE" : "DUE",
        receiptNumber: isPaid ? `RCP-2026-10${String(i + 1).padStart(2, "0")}` : undefined,
        collectedByAgentId: isPaid ? "USR-02" : undefined,
      };
    })
  },
  {
    id: "LN-02",
    loanNumber: "LN-2026-0102",
    customerId: "CUST-02",
    customerName: "P. Lakshmi Durga",
    customerCode: "CUST-RJY-002",
    customerPhone: "+91 99490 88219",
    areaId: "AREA-01",
    areaName: "Rajahmundry",
    routeId: "RT-02",
    routeName: "Route B - Main Bazaar & Syamala Theatre Road",
    loanType: "MONTHLY",
    principalAmount: 50000,
    interestRatePercentage: 15,
    totalInterestAmount: 7500,
    totalRepayableAmount: 57500,
    installmentAmount: 4792,
    durationUnits: 12,
    disbursementDate: "2026-02-15",
    startDate: "2026-03-15",
    endDate: "2027-02-15",
    totalPaidAmount: 33540,
    outstandingBalance: 23960,
    nextDueDate: "2026-10-15",
    status: "ACTIVE",
    agentId: "USR-03",
    agentName: "Suresh Babu",
    remarks: "Textile festive inventory stock expansion",
    installments: Array.from({ length: 12 }, (_, i) => {
      const isPaid = i < 7;
      return {
        installmentNumber: i + 1,
        dueDate: `2026-${String((i + 3) <= 12 ? i + 3 : (i + 3) - 12).padStart(2, "0")}-15`,
        amount: 4792,
        paidAmount: isPaid ? 4792 : 0,
        paidDate: isPaid ? `2026-${String(i + 3).padStart(2, "0")}-15` : undefined,
        status: isPaid ? "PAID" : i === 7 ? "DUE" : "DUE",
        receiptNumber: isPaid ? `RCP-2026-20${String(i + 1).padStart(2, "0")}` : undefined,
        collectedByAgentId: isPaid ? "USR-03" : undefined,
      };
    })
  },
  {
    id: "LN-03",
    loanNumber: "LN-2026-0103",
    customerId: "CUST-03",
    customerName: "K. Appa Rao",
    customerCode: "CUST-KKD-003",
    customerPhone: "+91 94901 77654",
    areaId: "AREA-02",
    areaName: "Kakinada",
    routeId: "RT-03",
    routeName: "Route C - Bhanugudi & Cinema Road",
    loanType: "PRODUCT_FINANCE",
    productName: "Hero Splendor Plus XTEC Motorcycle",
    productId: "PROD-05",
    principalAmount: 70000,
    interestRatePercentage: 18,
    totalInterestAmount: 12600,
    totalRepayableAmount: 82600,
    installmentAmount: 4588,
    durationUnits: 18,
    disbursementDate: "2026-01-10",
    startDate: "2026-02-10",
    endDate: "2027-07-10",
    totalPaidAmount: 47600,
    outstandingBalance: 35000,
    nextDueDate: "2026-09-20",
    status: "ACTIVE",
    agentId: "USR-04",
    agentName: "Venkat Rao",
    remarks: "Two-wheeler commercial delivery vehicle finance",
    installments: []
  },
  {
    id: "LN-04",
    loanNumber: "LN-2026-0104",
    customerId: "CUST-04",
    customerName: "G. Venkateswara Rao",
    customerCode: "CUST-AMP-004",
    customerPhone: "+91 98495 66781",
    areaId: "AREA-03",
    areaName: "Amalapuram",
    routeId: "RT-04",
    routeName: "Route D - Clock Tower & Peruru Road",
    loanType: "MONTHLY",
    principalAmount: 50000,
    interestRatePercentage: 15,
    totalInterestAmount: 7500,
    totalRepayableAmount: 57500,
    installmentAmount: 4792,
    durationUnits: 12,
    disbursementDate: "2026-01-20",
    startDate: "2026-02-20",
    endDate: "2027-01-20",
    totalPaidAmount: 38332,
    outstandingBalance: 19168,
    nextDueDate: "2026-09-20",
    status: "ACTIVE",
    agentId: "USR-05",
    agentName: "Prasad Raju",
    remarks: "Coconut trade working capital",
    installments: []
  },
  {
    id: "LN-05",
    loanNumber: "LN-2026-0105",
    customerId: "CUST-05",
    customerName: "T. Krishna Chaitanya",
    customerCode: "CUST-RCP-005",
    customerPhone: "+91 97011 22345",
    areaId: "AREA-04",
    areaName: "Ramachandrapuram",
    routeId: "RT-05",
    routeName: "Route E - Market Line & RTC Complex",
    loanType: "WEEKLY",
    principalAmount: 10000,
    interestRatePercentage: 20,
    totalInterestAmount: 2000,
    totalRepayableAmount: 12000,
    installmentAmount: 600,
    durationUnits: 20,
    disbursementDate: "2026-06-15",
    startDate: "2026-06-22",
    endDate: "2026-11-09",
    totalPaidAmount: 7800,
    outstandingBalance: 4200,
    nextDueDate: "2026-09-22",
    status: "ACTIVE",
    agentId: "USR-02",
    agentName: "Ramesh Varma",
    remarks: "Weekly mini business loan",
    installments: []
  },
  {
    id: "LN-06",
    loanNumber: "LN-2026-0106",
    customerId: "CUST-07",
    customerName: "V. Chinna Reddemma",
    customerCode: "CUST-KKD-007",
    customerPhone: "+91 94411 99887",
    areaId: "AREA-02",
    areaName: "Kakinada",
    routeId: "RT-03",
    routeName: "Route C - Bhanugudi & Cinema Road",
    loanType: "WEEKLY",
    principalAmount: 30000,
    interestRatePercentage: 20,
    totalInterestAmount: 6000,
    totalRepayableAmount: 36000,
    installmentAmount: 1800,
    durationUnits: 20,
    disbursementDate: "2026-03-01",
    startDate: "2026-03-08",
    endDate: "2026-07-26",
    totalPaidAmount: 8000,
    outstandingBalance: 28000,
    nextDueDate: "2026-04-12",
    status: "OVERDUE",
    agentId: "USR-04",
    agentName: "Venkat Rao",
    remarks: "Defaulted on 6 consecutive installments. Legal notice sent.",
    installments: []
  }
];

export const initialProducts: Product[] = [
  {
    id: "PROD-01",
    sku: "PROD-IPHONE15",
    name: "Apple iPhone 15 (128GB Black)",
    category: "MOBILE",
    brand: "Apple",
    productCost: 59000,
    sellingPrice: 69900,
    stockQuantity: 12,
    standardDownPayment: 15000,
    standardTenureMonths: 12,
    status: "IN_STOCK",
  },
  {
    id: "PROD-02",
    sku: "PROD-LG-55TV",
    name: "LG 55-inch 4K UHD Smart OLED TV",
    category: "TV",
    brand: "LG Electronics",
    productCost: 42000,
    sellingPrice: 52500,
    stockQuantity: 8,
    standardDownPayment: 10000,
    standardTenureMonths: 10,
    status: "IN_STOCK",
  },
  {
    id: "PROD-03",
    sku: "PROD-WHIRL-REF",
    name: "Whirlpool 260L Frost-Free Double Door Refrigerator",
    category: "REFRIGERATOR",
    brand: "Whirlpool",
    productCost: 23500,
    sellingPrice: 29900,
    stockQuantity: 4,
    standardDownPayment: 6000,
    standardTenureMonths: 8,
    status: "LOW_STOCK",
  },
  {
    id: "PROD-04",
    sku: "PROD-IFB-WM",
    name: "IFB 7kg 5-Star Front Load Washing Machine",
    category: "WASHING_MACHINE",
    brand: "IFB",
    productCost: 28000,
    sellingPrice: 34990,
    stockQuantity: 6,
    standardDownPayment: 7000,
    standardTenureMonths: 9,
    status: "IN_STOCK",
  },
  {
    id: "PROD-05",
    sku: "PROD-HERO-SPL",
    name: "Hero Splendor Plus XTEC 100cc Motorcycle",
    category: "MOTORCYCLE",
    brand: "Hero MotoCorp",
    productCost: 68000,
    sellingPrice: 84000,
    stockQuantity: 3,
    standardDownPayment: 14000,
    standardTenureMonths: 18,
    status: "LOW_STOCK",
  }
];

export const initialProductFinanceOrders: ProductFinanceOrder[] = [
  {
    id: "PFO-01",
    orderNumber: "PFO-2026-081",
    productId: "PROD-05",
    productName: "Hero Splendor Plus XTEC 100cc Motorcycle",
    category: "MOTORCYCLE",
    customerId: "CUST-03",
    customerName: "K. Appa Rao",
    customerCode: "CUST-KKD-003",
    customerPhone: "+91 94901 77654",
    loanId: "LN-03",
    productCost: 68000,
    sellingPrice: 84000,
    downPayment: 14000,
    financedAmount: 70000,
    profitMargin: 28600, // 16000 retail profit + 12600 interest
    tenureMonths: 18,
    monthlyEmi: 4588,
    orderDate: "2026-01-10",
    status: "ACTIVE",
    serialNumber: "MBN-2026-8890214",
  },
  {
    id: "PFO-02",
    orderNumber: "PFO-2026-082",
    productId: "PROD-02",
    productName: "LG 55-inch 4K UHD Smart OLED TV",
    category: "TV",
    customerId: "CUST-06",
    customerName: "M. Anitha Kumari",
    customerCode: "CUST-RJY-006",
    customerPhone: "+91 99890 12344",
    loanId: "LN-07",
    productCost: 42000,
    sellingPrice: 52500,
    downPayment: 12500,
    financedAmount: 40000,
    profitMargin: 16500,
    tenureMonths: 10,
    monthlyEmi: 4600,
    orderDate: "2026-08-15",
    status: "ACTIVE",
    serialNumber: "LG-TV-55-99201",
  }
];

export const initialCollections: Collection[] = [
  {
    id: "COL-01",
    receiptNumber: "RCP-2026-8891",
    customerId: "CUST-01",
    customerName: "B. Satyanarayana Murthy",
    customerCode: "CUST-RJY-001",
    loanId: "LN-01",
    loanNumber: "LN-2026-0101",
    agentId: "USR-02",
    agentName: "Ramesh Varma",
    amount: 1200,
    paymentMethod: "CASH",
    collectionDate: "2026-09-20",
    time: "09:15 AM",
    areaName: "Rajahmundry",
    routeName: "Route A - Danavaipeta & Kotagummam",
    installmentNumber: 15,
    balanceAfterPayment: 6000,
    remarks: "Received weekly installment #15 at store counter",
  },
  {
    id: "COL-02",
    receiptNumber: "RCP-2026-8892",
    customerId: "CUST-03",
    customerName: "K. Appa Rao",
    customerCode: "CUST-KKD-003",
    loanId: "LN-03",
    loanNumber: "LN-2026-0103",
    agentId: "USR-04",
    agentName: "Venkat Rao",
    amount: 4588,
    paymentMethod: "UPI",
    upiTransactionId: "UPI/3902198402/SBI",
    collectionDate: "2026-09-20",
    time: "10:30 AM",
    areaName: "Kakinada",
    routeName: "Route C - Bhanugudi & Cinema Road",
    installmentNumber: 11,
    balanceAfterPayment: 30412,
    remarks: "Monthly EMI paid via PhonePe QR",
  },
  {
    id: "COL-03",
    receiptNumber: "RCP-2026-8893",
    customerId: "CUST-04",
    customerName: "G. Venkateswara Rao",
    customerCode: "CUST-AMP-004",
    loanId: "LN-04",
    loanNumber: "LN-2026-0104",
    agentId: "USR-05",
    agentName: "Prasad Raju",
    amount: 4792,
    paymentMethod: "CASH",
    collectionDate: "2026-09-20",
    time: "11:10 AM",
    areaName: "Amalapuram",
    routeName: "Route D - Clock Tower & Peruru Road",
    installmentNumber: 9,
    balanceAfterPayment: 14376,
    remarks: "Collected at coconut mandi yard",
  },
  {
    id: "COL-04",
    receiptNumber: "RCP-2026-8894",
    customerId: "CUST-05",
    customerName: "T. Krishna Chaitanya",
    customerCode: "CUST-RCP-005",
    loanId: "LN-05",
    loanNumber: "LN-2026-0105",
    agentId: "USR-02",
    agentName: "Ramesh Varma",
    amount: 600,
    paymentMethod: "UPI",
    upiTransactionId: "UPI/9982348001/HDFC",
    collectionDate: "2026-09-20",
    time: "11:45 AM",
    areaName: "Ramachandrapuram",
    routeName: "Route E - Market Line & RTC Complex",
    installmentNumber: 14,
    balanceAfterPayment: 3600,
    remarks: "Weekly EMI paid via GPay",
  },
  {
    id: "COL-05",
    receiptNumber: "RCP-2026-8890",
    customerId: "CUST-02",
    customerName: "P. Lakshmi Durga",
    customerCode: "CUST-RJY-002",
    loanId: "LN-02",
    loanNumber: "LN-2026-0102",
    agentId: "USR-03",
    agentName: "Suresh Babu",
    amount: 4792,
    paymentMethod: "BANK_TRANSFER",
    upiTransactionId: "NEFT/IOB8892100",
    collectionDate: "2026-09-19",
    time: "04:30 PM",
    areaName: "Rajahmundry",
    routeName: "Route B - Main Bazaar & Syamala Theatre Road",
    installmentNumber: 8,
    balanceAfterPayment: 19168,
    remarks: "Bank direct deposit credited",
  }
];

export const initialExpenses: Expense[] = [
  {
    id: "EXP-01",
    voucherNumber: "VCH-2026-041",
    category: "FUEL",
    title: "Field Agent Petrol Allowance - Route A & E",
    amount: 1800,
    date: "2026-09-20",
    paidTo: "Ramesh Varma",
    paymentMethod: "UPI",
    approvedBy: "K. Srikanth Naidu",
    notes: "Weekly field travel reimbursement",
  },
  {
    id: "EXP-02",
    voucherNumber: "VCH-2026-042",
    category: "OFFICE_RENT",
    title: "Rajahmundry Branch Main Office Rent (Sep 2026)",
    amount: 22000,
    date: "2026-09-05",
    paidTo: "B. Ram Mohan (Landlord)",
    paymentMethod: "BANK_TRANSFER",
    approvedBy: "K. Srikanth Naidu",
    notes: "Main commercial branch rent",
  },
  {
    id: "EXP-03",
    voucherNumber: "VCH-2026-043",
    category: "SALARIES",
    title: "Field Agents & Staff Monthly Incentives",
    amount: 35000,
    date: "2026-09-10",
    paidTo: "Staff Payroll Account",
    paymentMethod: "BANK_TRANSFER",
    approvedBy: "K. Srikanth Naidu",
    notes: "August recovery performance bonuses",
  },
  {
    id: "EXP-04",
    voucherNumber: "VCH-2026-044",
    category: "MARKETING",
    title: "Diwali Loan Scheme Pamphlets & Auto Rickshaw Promo",
    amount: 4500,
    date: "2026-09-15",
    paidTo: "Sri Sai Graphics & Audio Ads",
    paymentMethod: "CASH",
    approvedBy: "K. Srikanth Naidu",
    notes: "Festive finance scheme outreach",
  },
  {
    id: "EXP-05",
    voucherNumber: "VCH-2026-045",
    category: "VEHICLE_MAINTENANCE",
    title: "Field Bike Servicing & Oil Change (AP 05 CP 4410)",
    amount: 1450,
    date: "2026-09-18",
    paidTo: "Venkateswara Motors",
    paymentMethod: "CASH",
    approvedBy: "K. Srikanth Naidu",
    notes: "Agent field vehicle servicing",
  }
];

export const initialNotifications: SystemNotification[] = [
  {
    id: "NOTIF-01",
    title: "Due Today Alert",
    message: "18 loan installments totaling ₹68,400 are scheduled for collection today across Rajahmundry and Kakinada routes.",
    type: "DUE_TODAY",
    timestamp: "10 mins ago",
    read: false,
    priority: "HIGH",
  },
  {
    id: "NOTIF-02",
    title: "Overdue Alert - V. Chinna Reddemma",
    message: "Loan LN-2026-0106 has breached 45 days overdue (₹28,000 pending). Defaulter notice pending review.",
    type: "OVERDUE",
    timestamp: "1 hour ago",
    read: false,
    priority: "HIGH",
  },
  {
    id: "NOTIF-03",
    title: "Low Product Stock Alert",
    message: "Whirlpool Double Door Refrigerators and Hero Splendor+ inventory reached critical threshold (≤4 units).",
    type: "LOW_STOCK",
    timestamp: "3 hours ago",
    read: false,
    priority: "MEDIUM",
  },
  {
    id: "NOTIF-04",
    title: "Agent Route Check-In",
    message: "Agent Ramesh Varma checked in on Route A (Danavaipeta) at 08:45 AM. Target: ₹28,800.",
    type: "ATTENDANCE",
    timestamp: "4 hours ago",
    read: true,
    priority: "LOW",
  }
];

export const initialAttendance: AgentAttendance[] = [
  {
    id: "ATT-01",
    agentId: "USR-02",
    agentName: "Ramesh Varma",
    date: "2026-09-20",
    checkInTime: "08:45 AM",
    status: "ON_FIELD",
    startKilometers: 14220,
    remarks: "Route A Danavaipeta collection run",
  },
  {
    id: "ATT-02",
    agentId: "USR-03",
    agentName: "Suresh Babu",
    date: "2026-09-20",
    checkInTime: "09:00 AM",
    status: "ON_FIELD",
    startKilometers: 8940,
    remarks: "Main Bazaar daily market collection",
  },
  {
    id: "ATT-03",
    agentId: "USR-04",
    agentName: "Venkat Rao",
    date: "2026-09-20",
    checkInTime: "08:50 AM",
    status: "ON_FIELD",
    startKilometers: 22100,
    remarks: "Bhanugudi & Port road collections",
  },
  {
    id: "ATT-04",
    agentId: "USR-05",
    agentName: "Prasad Raju",
    date: "2026-09-20",
    checkInTime: "09:15 AM",
    status: "PRESENT",
    startKilometers: 11500,
    remarks: "Office verification & Amalapuram route",
  }
];
